import Head from "next/head";
import Image from "next/image";
import { useEffect } from "react";
import MainPage from "../components/MainPage";
import Navbar from "../components/Navbar";
import styles from "../styles/Home.module.css";
import axios from "axios";

export default function Home() {
  useEffect(() => {
    axios
      .get("https://fakestoreapi.com/products")
      .then((res) => console.log(res))
      .catch((err) => console.log(err));
  }, []);
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainPage />
    </div>
  );
}
